env:
  es6: true
  browser: true
  node: true
settings:
  react:
    version: detect
parser: '@typescript-eslint/parser'
extends:
  - standard
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
plugins:
  - '@next/next'
  - '@typescript-eslint'
  - react
  - react-hooks
  - jsx-a11y
  - prettier
  - eslint-plugin-import-helpers
  - import
rules:
  indent: off
  semi: ['error', 'never']
  quotes: ['error', 'single']
  jsx-quotes: ['error', 'prefer-single']
  no-underscore-dangle: off
  react/jsx-filename-extension: ['error', { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  react/prop-types: off
  space-before-function-paren: off
  multiline-ternary: off
  no-use-before-define: off
  import-helpers/order-imports:
    [
      'warn',
      {
        newlinesBetween: 'always',
        groups:
          [
            '/^react/',
            'module',
            '/^@mui/material/',
            '/^@mui/lab/',
            '/^@mui/icons-material/',
            '/^@mui/styles/',
            '/^icons/',
            '/^components/',
            '/^dialogs/',
            '/^routes/',
            '/^containers/',
            '/^pages/',
            '/^contexts/',
            '/^forms/',
            '/^hooks/',
            '/^graphql/',
            '/^services/',
            '/^assets/',
            '/^utils/',
            '/^theme/',
            '/^types/',
            '/^styles/',
            ['parent', 'sibling', 'index']
          ],
        alphabetize: { order: 'asc', ignoreCase: true }
      }
    ]
